# Generated by Django 4.2.1 on 2023-05-10 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_student_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование')),
                ('description', models.CharField(max_length=150, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(max_length=150, verbose_name='Наименование')),
                ('description', models.CharField(max_length=150, verbose_name='Описание')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Изображение (превью)')),
                ('category', models.CharField(max_length=150, verbose_name='Категория')),
                ('price', models.IntegerField(verbose_name='Цена за покупку')),
                ('creation_date', models.DateTimeField(verbose_name='Дата создания')),
                ('last_modified_date', models.DateTimeField(verbose_name='Дата последнего изменения')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
