# Generated by Django 4.2.1 on 2023-05-10 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='last_modified_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата последнего изменения'),
        ),
    ]
